spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/binarfud
    username: postgres
    password: gajah
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibern
